### PR TITLE
#1250 issue : Updated registration.yaml

### PR DESCRIPTION
**Pull request by AllMightLegend**
To solve the issue of securely managing the as_token and hs_token in the application service registration YAML file, we can introduce the ability to specify file paths for these tokens (as_token_path and hs_token_path) instead of hardcoding the tokens directly in the YAML file.

### Pull Request Checklist

* [x] Pull request includes a [changelog file](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#adding-to-the-changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#sign-off)
* [x] Pull request is classified as ['other changes'](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#other-changes)

### CODE REVIEW

**Comment by KitsuneRal** [comment]
I'm sorry but this is not a good contribution and you don't seem to have read the contribution guidelines I linked to when responding to your previous contribution. You also ticked the boxes in the checklist without actually fulfilling the requirements stated: I don't see your sign-off; the changelog file, even though present, is malformed; and the changes you proposed cannot be considered as "other changes" because they alter the API, which normally means having to go through a proper proposal process (the contributing guidelines link to it). If you continue to disregard the guidelines described in [CONTRIBUTING.rst](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst) we may close your pull requests without further explanation.

**Comment by AllMightLegend** [comment]
I'm very sorry but I'm learning what to do right now.Please don't mind it sir.I will definitely work on it.Please give me a few chances

**Comment by AllMightLegend** [comment]
Can you please advise me on how to go around this issue.

**Comment by AllMightLegend** [comment]
Also I think I have understood most of the part of the contributions.rst file .But if I ever ask whether an issue will have to undergo the process proposal or not then will it be okay ??

**Pull request closed without merging**
