### PR TITLE
Clarify that invite->knock is *not* a valid transition

### PR DESCRIPTION
**Pull request by kegsay**
This reverts https://github.com/matrix-org/matrix-spec/pull/1175

See https://github.com/matrix-org/matrix-spec/issues/1710

Signed-off-by: Kegan Dougal <kegan@matrix.org>

Preview: https://pr1717--matrix-spec-previews.netlify.app

### CODE REVIEW

**Review by richvdh — APPROVED** [review]
As with https://github.com/matrix-org/matrix-spec-proposals/pull/4091: I think this is the right thing to do, but I would like opinions from others.

**Comment by richvdh** [comment]
Also worth linking here: a complement test that asserts that what is implemented matches what this PR says: https://github.com/matrix-org/complement/pull/702.

**Review by dbkr — APPROVED** [review]
Thanks, I agree this is the correct way out of the mess, and doubly so with the complement test.

**Pull request merged**
