### PR TITLE
Fix enum types in JSON schemas

### PR DESCRIPTION
**Pull request by zecakeh**
`type: enum` does not exist, as an enum can be of any type.

Preview: https://pr1634--matrix-spec-previews.netlify.app

### CODE REVIEW

**Review by KitsuneRal — APPROVED** [review]

**Comment by KitsuneRal** [comment]
That looks good, but should we also show `string` instead of `enum` in the spec text then? For consistency.

**Comment by zecakeh** [comment]
Sure we could do that, it should be simple enough. Do you want me to add a commit to this PR or should it be in another PR?

**Comment by KitsuneRal** [comment]
Just add another commit here.

**Review by richvdh — APPROVED** [review]
lgtm but maybe @KitsuneRal wants another look?

**Comment by richvdh** [comment]
Assuming kitsune is happy here.

**Pull request merged**
