### PR TITLE
Factor out all the common parameters of the various /relations apis

### PR DESCRIPTION
**Pull request by dbkr**
This doesn't currently work, perhaps because the template needs to resolve refs?

Things this PR needs:
 * [ ] https://github.com/matrix-org/matrix-spec/pull/1749 merged
 * [ ] Replace other instances of params
 * [ ] Do the same to responses
 * [ ] CI happy

Preview: https://pr1745--matrix-spec-previews.netlify.app

### CODE REVIEW

**Comment by dbkr** [comment]
Apparently: "the ref partial doesn't support references using fragments yet"

**Comment by richvdh** [comment]
Hopefully I've fixed this in #1749, which I have now merged in here.

**Comment by dbkr** [comment]
Awesome, thank you for doing that. So this just needs a newsfile and it's ready to go?

**Comment by dbkr** [comment]
Ah no, I'll add a checklist to the description.

**Comment by richvdh** [comment]
sorry, I'm still thrashing this out with @zecakeh

**Comment by richvdh** [comment]
Right, #1751 has landed, so I'm going to rebase this again

**Review by richvdh — APPROVED** [review]

**Pull request merged**
