### PR TITLE
634 issue : Replace "OpenMarket Ltd" with "The Matrix.org Foundation …

### PR DESCRIPTION
**Pull request by Aman-Sigroha**
…C.I.C." in copyright notices

Fixes https://github.com/matrix-org/matrix-spec/issues/634

### Pull Request Checklist

* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#adding-to-the-changelog)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#sign-off)
* [ ] Pull request is classified as ['other changes'](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#other-changes)

### CODE REVIEW

**Comment by KitsuneRal** [comment]
I don't think it's correct. The Foundation didn't exist in 2016, for one.

**Comment by sumnerevans** [comment]
Relevant issue is https://github.com/matrix-org/matrix-spec/issues/634

Probably should discuss there whether the copyright change is correct.

**Comment by tulir** [comment]
The Synapse issue linked in #634 seems to have discussed that already and found that the change is correct https://github.com/matrix-org/synapse/issues/7565#issuecomment-639171606

**Comment by KitsuneRal** [comment]
Oh, okay, I remember now the copyrights were reassigned back in the time. Still, what the previous comment says. Thanks for digging it.

**Pull request closed without merging**
