### PR TITLE
#1383 issue : Update edu.yaml

### PR DESCRIPTION
**Pull request by AllMightLegend**
### Pull Request Checklist

"m.presence" is changed to "m.typing" as here edu has no reason for presence.
* [x] Pull request is classified as ['other changes'](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#other-changes)

Preview: https://pr1921--matrix-spec-previews.netlify.app

### CODE REVIEW

**Comment by turt2live** [comment]
Thanks for the PR! It appears as though some generated output is included, and the checklist has been marked complete without the changes being visible to us. Please review the links on the checklist for more details on what we're expecting.

A descriptive title and link to the issue you're fixing in the PR description would also be appreciated.

**Comment by AllMightLegend** [comment]
Okay will definitely work on it.But sir can you give me a heads up about the failed check newsfragments !!!

**Comment by AllMightLegend** [comment]
I am very new to open source contribution sir. I would appreciate your help please.

**Comment by AllMightLegend** [comment]
The thing is I have changed the edu.yaml file but the error is for checking the newsfragments

**Comment by KitsuneRal** [comment]
@AllMightLegend, welcome to the community.
1. The README text that you probably have seen at https://github.com/matrix-org/matrix-spec, advises you to read [CONTRIBUTING.rst](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst) for details on how to contribute. The part about newsfragments is explained there.
2. As @turt2live said, your contribution includes files that you probably did not intend to contribute. When you commit the changes locally, I strongly recommend to review the difference with the base Git commit and only select the files that you intend to contribute. You apparently used VSCode to edit `edu.yaml` and it added extra files to `.history/` folder that our project has nothing to do with. You can remove these files from the pull request by removing them and committing+pushing the removal action.

**Comment by AllMightLegend** [comment]
Thank you sir let me do it and see.

**Pull request closed without merging**
