### PR TITLE
Use A(E) and B(E) for state after/before events

### PR DESCRIPTION
**Pull request by DMRobertson**
A suggestion to mitigate #774.

Preview: https://pr1040--matrix-spec-previews.netlify.app

### CODE REVIEW

**Comment by DMRobertson** [comment]
Created with

```shell
sed -e 's/\*S\*(/*B*(/g' -e "s/\*S\*′(/*A*(/g" -i content/rooms/{fragments/v2-state-res.md,v1.md}
```

**Comment by uhoreg** [comment]
I like the idea in general, but I'm not sure about using "A" and "B", since "A" comes before "B" in the alphabet, so, at least for me, my brain gets confused about which one represents the earlier state, and which one is the later state.

**Comment by DMRobertson** [comment]
Could try `I(E)` and`F(E)` for initial and final?

Could also try including the prime in the `<em>`. I can experiment a little next week.

**Comment by DMRobertson** [comment]
Could also use the notation *P*(*E*) to mean "the state prior to *E*".

**Comment by DMRobertson** [comment]
> Could also try including the prime in the `<em>`. I can experiment a little next week.

See #1043.

**Comment by uhoreg** [comment]
"I" and "F" for "Initial" and "Final" would probably work.  It also suffers from the unfortunate fact that "I" comes after "F" in the alphabet, but they're far enough apart (and not at the beginning of the alphabet) that it doesn't trigger my "I don't know what order it's supposed to be" response.

**Comment by turt2live** [comment]
@uhoreg as the sole SCT commenter on here, does https://github.com/matrix-org/matrix-spec/pull/1043 alleviate the concern enough or is there still work to be done here?

**Comment by uhoreg** [comment]
While #1043 makes the primes more visible, primes can be somewhat foreign to many people, so I think there's still value in doing something along the lines of what this PR is trying to do.  On the other hand, this PR now has conflicts with the main branch (presumably because of 1043), so it may be easier to create a new PR, rather than trying to fix this one up.

I'd be inclined to let @DMRobertson decide how to proceed with this particular PR.

**Comment by DMRobertson** [comment]
No strong opinions. #1043 makes things readable enough for me. If there's no obvious better notation, let's leave as-is.

**Pull request closed without merging**
