### PR TITLE
strike element is deprecated, s replaces it

### PR DESCRIPTION
**Pull request by cloudrac3r**
### Pull Request Checklist

* [x] Pull request includes a [changelog file](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#adding-to-the-changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#sign-off)
* [x] Pull request is classified as ['other changes'](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#other-changes)

### Description

The [strike](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike) element is deprecated in the HTML spec. Clients should prefer [s](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s) instead if they wish to mark text with strikethrough without semantic meaning.

As far as I am aware, no client actually supports sending messages with strikethrough formatting, so this shouldn't affect current compatibility.

I hope I filled out this PR template correctly :)

Signed-off-by: Cadence Ember <cadence@disroot.org>

Preview: https://pr1629--matrix-spec-previews.netlify.app

### CODE REVIEW

**Comment by KitsuneRal** [comment]
Well, in fact, a few clients support sending raw HTML (I just checked Quaternion and Element Web for a very quick check), and although Quaternion still converts `<strike>` to `<del>` even when sent as raw HTML, Element Web doesn't do that and faithfully sends `<strike>` to the homeserver. I'm afraid this would require a (very simple) MSC therefore.

**Comment by MTRNord** [comment]
I think the current state is more confusing considering the syntax ele Web input for example uses is `<del>` and not any of the others.

**Comment by KitsuneRal** [comment]
Well it's the same old HTML story - `<strong>` vs. `<b>` etc. `<del>` is in the recommended list of tags just as well; even though the tags are sort-of similar semantically, replacing `<strike>` with `<s>` is orthogonal to having `<del>` around.

**Comment by richvdh** [comment]
Closing this for now. As others have noted, we'll need an MSC.

**Comment by anoadragon453** [comment]
Re-opening as per @cloudrac3r's [request](https://github.com/matrix-org/matrix-spec/pull/1629#issuecomment-1963109725).

**Review by turt2live — APPROVED** [review]
Thanks!

**Pull request merged**
