### PR TITLE
Remove `keyId` from the server keys endpoints

### PR DESCRIPTION
**Pull request by zecakeh**
Spec PR for [MSC3938](https://github.com/matrix-org/matrix-spec-proposals/pull/3938).

This is a prerequisite for #1310.

Signed-off-by: Kévin Commaille <zecakeh@tedomum.fr>

Preview: https://pr1350--matrix-spec-previews.netlify.app

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
Deprecated endpoints require an MSC to remove them.

**Comment by richvdh** [comment]
> Deprecated endpoints require an MSC to remove them.

I mean, really? Isn't the fact that they are deprecated enough of an indication that if people care about them they need to make a case to *undeprecate* them?

**Comment by richvdh** [comment]
ugh, what a pain in the ass. I think we should revise that.

**Comment by turt2live** [comment]
it'd only take an MSC 😇 

I'm fairly opposed to changing the policy here, but that's a discussion for elsewhere.

**Comment by richvdh** [comment]
I've opened https://github.com/matrix-org/matrix-spec-proposals/pull/3938.

**Comment by zecakeh** [comment]
I updated the description and changelog entry to mention [MSC3938](https://github.com/matrix-org/matrix-spec-proposals/pull/3938).

**Review by turt2live — APPROVED** [review]
Thanks!

**Pull request merged**
