### PR TITLE
appendices.md: expand URI scheme by actions to include knock

### PR DESCRIPTION
**Pull request by Mikaela**
Resolves: #1015

Signed-off-by: Aminda Suomalainen <suomalainen+git@mikaela.info>

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
This is not listed in any MSC as possible, so requires an MSC to be incorporated within the spec.

**Comment by Mikaela** [comment]
Oh, I thought by https://github.com/matrix-org/matrix-spec/issues/1015#event-6349796280 you meant it's not necessary. I have no idea how to work the MSC process so I am giving this up in hopes the issue is enough for it to happen in the future.

**Comment by richvdh** [comment]
MSC process: open a PR adding a file to https://github.com/matrix-org/matrix-spec-proposals/tree/main/proposals, explaining what needs changing and why.

That's it. Please don't imagine that it's some massive complicated thing.

**Comment by Mikaela** [comment]
@richvdh Would it be possible to have this documented somewhere where it might actually be found such as CONTRIBUTING.md to the repository in question? The repository doesn't currently even have a README, and as my only experience is reviewing or suggesting changes in MSCs others have written, I don't know how I should imagine it to work.

**Pull request closed without merging**
